spring:
  profiles:
    active: default
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(u4xFmUig6m6OSM0oa30LOamRWI+YrR42fSbEGWzcaI5meDYH0Rc4VvacsB9rrXJcZaWjoLHhb1aciYqY5Y4KqT0rcfL6nFtceyaiTK+rn/Rt0bQc79f1PxwGtU+ZMNM8WEgU68Z16Ns=)
    username: ENC(yBOaAlgdmHgfFJyVMxwVGQ==)
    password: ENC(6Yy5Dr9lpyzG7+vAkmJhqw/1XkskdNAg)
  jpa:
#    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
        format_sql: true

resources:
    static-locations: /resources/

springdoc:
  default-consumes-media-type : application/json
  default-produces-media-type : application/json
  model-and-view-allowed: true
  api-docs:
    groups:
      enabled: true
  swagger-ui:
    disable-swagger-default-url : true
    doc-expansion: none
    tags-sorter: alpha
    operations-sorter: alpha
    path : /swagger-ui.html
#logging:
#  level:
#    com.recruit.configmate: info
---
spring:
  profiles: release
  # 여기는 서버에서 사용할 데이터베이스 주소 입력 똑같으면 안하셔도 됩니다.
  # datasource:
  #   driver-class-name: org.h2.Driver
  #   url: "jdbc:h2:tcp://localhost/~/test"
  #   username: root
  #   password: root